backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Featured Image Description", name: "featuredImageDescription", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "categories", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list" }